new URL for CenOS Stream 8 koji
rpm-software-management/mock pull request #1046
Opened 2023-03-09 20:42 UTC by xsuchy

Fixes: #1045

2023-03-09 20:42 UTC, Conan-Kudo approved these changes

2023-03-09 20:43 UTC, xsuchy commented
Do not merge until this URL is actually working - hopefully in a day or two.

2023-03-09 21:05 UTC, hroncok requested changes
It works, but the URL is different.

2023-03-09 21:05 UTC, hroncok commented on mock-core-configs/etc/mock/templates/centos-stream-8.tpl
> +baseurl=https://kojihub.stream.centos.org/kojifiles/repos/dist-c{{ releasever }}-stream-build/latest/$basearch/
```suggestion
baseurl=https://kojihub.stream.centos.org/kojifiles/repos/c{{ releasever }}s-build/latest/$basearch/
```

2023-03-09 21:12 UTC, xsuchy commented on mock-core-configs/etc/mock/templates/centos-stream-8.tpl
> +baseurl=https://kojihub.stream.centos.org/kojifiles/repos/dist-c{{ releasever }}-stream-build/latest/$basearch/
Thank you.

2023-03-09 21:13 UTC, xsuchy commented
Updated per suggestion and ready for review.

2023-03-10 00:23 UTC, Conan-Kudo approved these changes

2023-03-13 13:45 UTC, praiskup approved these changes

2023-03-13 13:46 UTC, merged