Show ccache stats at the end of the build
rpm-software-management/mock pull request #1299
Opened 2024-01-30 16:07 UTC by brianjmurrell

Zero the ccache stats at the beginning of the build and then display the ccache stats at the end of the build to see how effective ccache was.

2024-01-30 16:08 UTC, pep8speaks commented
Hello @brianjmurrell! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`mock/py/mockbuild/plugins/ccache.py`](https://github.com/rpm-software-management/mock/blob/e87d916d7f49ea4949973adf0f09e9e5bf891e03/mock/py/mockbuild/plugins/ccache.py):

> [Line 74:1](https://github.com/rpm-software-management/mock/blob/e87d916d7f49ea4949973adf0f09e9e5bf891e03/mock/py/mockbuild/plugins/ccache.py#L74): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 0

2024-01-31 06:21 UTC, praiskup commented on mock/py/mockbuild/plugins/ccache.py
> +        self.buildroot.doChroot(["ccache", "--zero-stats"], printOutput=True, shell=False)
Could you please wrap this command into a separate method, and call it twice?

2024-01-31 06:22 UTC, praiskup commented on mock/py/mockbuild/plugins/ccache.py
> +        self.buildroot.doChroot(["ccache", "--zero-stats"], printOutput=True, shell=False)
Could we ignore the exit status?  Just in case the `--zero-stats` option was unavailable in the target chroot.

2024-01-31 06:22 UTC, praiskup commented
Thank you for the PR!

2024-02-06 13:23 UTC, praiskup commented
Gently ping, please consider updating this if you want to meet the release #1307

2024-02-06 13:28 UTC, brianjmurrell commented
> Gently ping, please consider updating this if you want to meet the release #1307

It's on my TODO list.  Unfortunately behind some higher priority tasks.  I'll try to get to it soon.

2024-02-14 11:53 UTC, praiskup requested changes
Two small fixes requested above.

2024-08-05 07:37 UTC, xsuchy commented
@brianjmurrell any progress?

2024-09-10 11:07 UTC, praiskup commented on mock/py/mockbuild/plugins/ccache.py
> +        self.buildroot.doChroot(["ccache", "--zero-stats"], printOutput=True, shell=False)
I made the feature opt-in instead.

2024-09-10 11:08 UTC, praiskup approved these changes

2024-09-10 11:17 UTC, praiskup commented
The third call of F41 cpio.rpm:
```
INFO: ccache stats:
Cacheable calls:   346 / 622 (55.63%)
  Hits:            346 / 346 (100.0%)
    Direct:          3 / 346 ( 0.87%)
    Preprocessed:  343 / 346 (99.13%)
  Misses:            0 / 346 ( 0.00%)
Uncacheable calls: 276 / 622 (44.37%)
Local storage:
  Cache size (GB): 0.0 / 4.0 ( 0.10%)
  Hits:            346 / 346 (100.0%)
  Misses:            0 / 346 ( 0.00%)
```

2024-09-10 11:38 UTC, praiskup commented
The second run:
```
Cacheable calls:   346 / 622 (55.63%)
  Hits:              1 / 346 ( 0.29%)
    Direct:          1 /   1 (100.0%)
    Preprocessed:    0 /   1 ( 0.00%)
  Misses:          345 / 346 (99.71%)
Uncacheable calls: 276 / 622 (44.37%)
Local storage:
  Cache size (GB): 0.0 / 4.0 ( 0.10%)
  Hits:              1 / 346 ( 0.29%)
  Misses:          345 / 346 (99.71%)
```
I'd expect it to have usable caches even in the 2nd attempt, but that actually might be other problem (the original motivation for adding this feature)

2024-09-10 19:14 UTC, xsuchy approved these changes

2024-09-11 06:00 UTC, merged