config: Replace Mageia 10 and Cauldron i586 configs with i686
rpm-software-management/mock pull request #1360
Opened 2024-04-12 19:41 UTC by wally-mageia

Mageia replaced i586 arch with i686 in Cauldron, and thus also for upcoming Mageia 10.

2024-04-13 00:00 UTC, Conan-Kudo approved these changes

2024-04-13 00:01 UTC, Conan-Kudo requested changes
Can you please add a changelog entry?

2024-04-13 05:01 UTC, wally-mageia commented
> Can you please add a changelog entry?

Should be OK now.

2024-04-13 10:02 UTC, Conan-Kudo approved these changes

2024-04-23 06:42 UTC, merged

2024-04-23 06:42 UTC, praiskup commented
Thank you!