configs: fix openSUSE-tumbleweed update failure during the second build.
rpm-software-management/mock pull request #1507
Opened 2024-11-18 17:22 UTC by kilesduli

Fixes: #1506

2024-11-20 07:50 UTC, praiskup commented
PASSED: opensuse-tumbleweed-i586.cfg (tmpfs)
PASSED: opensuse-tumbleweed-i586.cfg
PASSED: opensuse-tumbleweed-x86_64.cfg (tmpfs)
PASSED: opensuse-tumbleweed-x86_64.cfg

2024-11-20 07:52 UTC, praiskup commented
We don't have an assigned maintainer for these openSUSE configuration files https://rpm-software-management.github.io/mock/Mock-Core-Configs

2024-11-20 07:54 UTC, praiskup commented
@lkocman @Conan-Kudo @kilesduli - would you mind to step-in and help with the maintenance?

2024-11-20 11:12 UTC, kilesduli commented
> @lkocman @Conan-Kudo @kilesduli - would you mind to step-in and help with the maintenance?

Sorry, I'm not familiar with openSUSE. This issue just came up while I was trying to build something on it by chance, so I'm afraid I can't help with the maintenance.

2024-11-21 13:35 UTC, Conan-Kudo requested changes

2024-11-21 13:35 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl
> +config_opts['chroot_setup_cmd'] = 'install patterns-devel-base-devel_rpm_build openSUSE-release-ftp rpm-repos-openSUSE-Tumbleweed'
This should be `openSUSE-release` instead of `openSUSE-release-ftp`. Otherwise this is good.

2024-11-21 14:30 UTC, Conan-Kudo commented
Can you squash into a single commit please?

2024-11-21 14:37 UTC, kilesduli commented
Ok, all thing done:)

> Can you squash into a single commit please?

I still have question. Should we include openSUSE-build-key in command? It's a dependency of rpm-repos-openSUSE-Tumbleweed. I saw it in the dnf history of tumbleweed-dnf.

2024-11-21 14:44 UTC, Conan-Kudo approved these changes

2024-11-21 21:08 UTC, praiskup commented
```
PASSED: opensuse-tumbleweed-i586.cfg (tmpfs)
PASSED: opensuse-tumbleweed-i586.cfg
PASSED: opensuse-tumbleweed-x86_64.cfg (tmpfs)
PASSED: opensuse-tumbleweed-x86_64.cfg

2024-11-21 21:08 UTC, praiskup approved these changes

2024-11-21 21:09 UTC, merged