new core-config: support almalinux
rpm-software-management/mock pull request #703
Opened 2021-02-13 01:19 UTC by prymar56

Signed-off-by: Mark Pryor <pryorm09@gmail.com>These are the 2 files, *tpl and *cfg, to support almalinux in latest mock.

2021-02-13 01:26 UTC, Conan-Kudo requested changes
Thanks for making this submission!
 
 Here's some initial feedback on how to get this into better shape to be included.

2021-02-13 01:26 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/alma-8-x86_64.cfg
> +include('/etc/mock/templates/epel-8.tpl.rpmnew')
This file doesn't exist.

2021-02-13 01:26 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/alma-8-x86_64.cfg
> +config_opts['root'] = 'alma-8-x86_64'
This can be put into the template file and structured to change correctly per-architecture.

2021-02-13 01:26 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/alma-8-x86_64.cfg
> +"""
This needs to be dropped.

2021-02-13 01:26 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/alma-8-x86_64.cfg
> +config_opts['chroot_setup_cmd'] += ' rpm-build nano dnf dnf-plugins-core glibc-langpack-en '
This is redundant with what you have in the template file and should be dropped.

2021-02-13 01:26 UTC, Conan-Kudo commented on mock-core-configs/etc/mock/templates/alma-8.tpl
> +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
Several issues here:

* This references AlmaLinux 8.3 but doesn't set a fixed path, should it be "AlmaLinux 8"?
* GPG check is turned off
* Path to the GPG key file is invalid, the key needs to be added to [xsuchy/distribution-gpg-keys](https://github.com/xsuchy/distribution-gpg-keys) like all the others have

2021-02-13 09:33 UTC, xsuchy commented
I just added Alma to distribution-gpg-keys in https://github.com/xsuchy/distribution-gpg-keys/commit/492dbff707a8c08461bb1cd6d066e2f9860278b1
Please use the path `/usr/share/distribution-gpg-keys/RPM-GPG-KEY-AlmaLinux`
I will release new version of distribution-gpg-keys together with new mock-core-config as soon as this PR is merged - and I agree with all @Conan-Kudo comments.

2021-02-13 21:42 UTC, xsuchy commented on mock-core-configs/etc/mock/alma-8-x86_64.cfg
> +config_opts['environment']['HOSTNAME'] = 'mock'
Why these two lines about `hostname`? I guess this should go away unless you have some strong reason.

2021-02-13 21:46 UTC, Conan-Kudo commented
Generally, it might make sense to copy the `centos-8-*` configs and make the Alma Linux ones based on that.

2021-02-17 03:52 UTC, prymar56 commented
while testing almalinux mock configs on fc33, I noticed that without enabling bootstrap, the rpmdb in /var/lib/rpm is sqlite.
This will break rpm when using the alma chroot for tests. Solution is to convert it from fc33.

Run this post-instll from fc33:
sudo rpmdb --rebuilddb --define "_db_backend bdb" --root /var/lib/mock/alma-8-x86_64/root

2021-02-17 11:57 UTC, Conan-Kudo commented
Yeah, Mock's default behavior is to use bootstrap mode, so this shouldn't be an issue in practice.

2021-02-22 09:53 UTC, praiskup commented
> Generally, it might make sense to copy the centos-8-* configs and make the Alma Linux ones based on that.

This makes sense to me as well.

2021-03-21 16:04 UTC, xsuchy commented
@prymar56 ping, any progress on fixing issues mentioned in comments?

2021-04-02 16:22 UTC, Conan-Kudo commented
@xsuchy @praiskup Due to lack of response by the submitter and the new release of Alma 8 stable, I've made #716 to replace this.

2021-04-03 12:45 UTC, xsuchy commented
Closing this one in favour of #716

2021-04-03 12:45 UTC, closed without merging