mock-core-configs: add configs for the CentOS Hyperscale SIG
rpm-software-management/mock pull request #722
Opened 2021-04-16 21:35 UTC by davide125

Add mock configs for building packages against the Hyperscale SIG repos in CentOS Stream. The GPG key was previously added in https://github.com/xsuchy/distribution-gpg-keys/pull/44

2021-04-16 21:38 UTC, Conan-Kudo requested changes
This should probably be called `centos-stream-8-hyperscale` instead of `hyperscale-8`. Otherwise there's no context for this config.

2021-04-16 21:40 UTC, Conan-Kudo commented
@davide125 Alternatively, we might want to have `centos-sig-mock-configs` package for all the SIGs there. Typically we've avoided all these layered things in `mock-core-configs`.

2021-04-16 21:41 UTC, davide125 commented
@Conan-Kudo yeah that works for me, I mostly just want to have these in a place easy to access. Would `mock-centos-sig-configs` still be a part of mock like `mock-core-configs` is, or would that be a wholly separate thing?

2021-04-16 21:42 UTC, Conan-Kudo commented
@davide125 It would be a totally separate project, and it would layer on top of `mock-core-configs`. I did this with `mock-mageia-configs` for Mageia: https://svnweb.mageia.org/packages/cauldron/mock-mageia-configs/current/

2021-04-16 21:46 UTC, davide125 commented
Ok, I've created https://pagure.io/centos-sig-hyperscale/mock-centos-sig-configs for this, let's continue there. Thanks!

2021-04-16 21:46 UTC, closed without merging

2021-04-17 06:41 UTC, xsuchy commented
@Conan-Kudo @davide125 It will be nice if you can put in your spec file:

Enhances: mock-core-configs

This is reverse dependency to `Suggests`. See https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/

2021-04-17 23:37 UTC, davide125 commented
thanks @xsuchy, I've added that in mock-centos-sig-configs-0.1-2: https://src.fedoraproject.org/rpms/mock-centos-sig-configs/c/2fd0ee62dffc058c486a873b5a161f773ab6bc10?branch=rawhide